version: '3'

services:

  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./web-files:/www:ro
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=www.fogliano.works enzo.fogliano.works heather.fogliano.works
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - REMOTE_PHP=myphp
      - REMOTE_PHP_PATH=/app
      - enzo.fogliano.works_REMOTE_PHP=myenzo
      - enzo.fogliano.works_REMOTE_PHP_PATH=/app
      - heather.fogliano.works_REMOTE_PHP=myheather
      - heather.fogliano.works_REMOTE_PHP_PATH=/app
    networks:
      - net1
      - net2
      - net3

  myphp:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files:/app

  myenzo:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files/enzo.fogliano.works:/app
    networks:
      - net1

  myheather:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files/heather.fogliano.works:/app
    networks:
      - net2
  
networks:
  net1:
  net2:
  net3: