version: '3'

services:

  mywww:
    image: bunkerity/bunkerized-nginx
    restart: always
    ports:
      - 80:8080
      - 443:8443
    volumes:
      - ./web-files:/www:ro
      - ./letsencrypt:/etc/letsencrypt
    environment:
      - SERVER_NAME=enzo.fogliano.works heather.fogliano.works admin.fogliano.works
      - MULTISITE=yes
      - AUTO_LETS_ENCRYPT=yes
      - REDIRECT_HTTP_TO_HTTPS=yes
      - DISABLE_DEFAULT_SERVER=yes
      - USE_CLIENT_CACHE=yes
      - USE_GZIP=yes
      - USE_BROTLI=yes
      - enzo.fogliano.works_REMOTE_PHP=myenzo
      - enzo.fogliano.works_REMOTE_PHP_PATH=/app
      - heather.fogliano.works_REMOTE_PHP=myheather
      - heather.fogliano.works_REMOTE_PHP_PATH=/app
      - admin.fogliano.works_SERVE_FILES=no
      - admin.fogliano.works_USE_AUTH_BASIC=yes
      - admin.fogliano.works_AUTH_BASIC_USER=admin
      - admin.fogliano.works_AUTH_BASIC_PASSWORD=admin
      - admin.fogliano.works_USE_REVERSE_PROXY=yes
      - admin.fogliano.works_REVERSE_PROXY_URL=/admin/
      - admin.fogliano.works_REVERSE_PROXY_HOST=http://myui:5000/
    labels: 
      - "bunkerized-nginx.UI"
    networks:
      - net1
      - net2
      - net3

  myenzo:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files/enzo.fogliano.works:/app
    networks:
      - net1

  myheather:
    image: php:fpm
    restart: always
    volumes:
      - ./web-files/heather.fogliano.works:/app
    networks:
      - net2
    
  myui:
    image: bunkerity/bunkerized-nginx-ui
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx
    environment:
      - ABSOLUTE_URI=https://admin.fogliano.works/admin/ 
  

networks:
  net1:
  net2:
  net3: